import { StyleSheet } from "react-native";
import { brand, ThemeColors } from "../../styles/theme";

export function createStyles(theme: ThemeColors) {
  return StyleSheet.create({
    screen: {
      flex: 1,
      backgroundColor: theme.bgPrimary,
    },
    scrollContent: {
      flexGrow: 1,
      justifyContent: "center",
      alignItems: "center",
      padding: 20,
    },
    card: {
      width: "100%",
      maxWidth: 400,
      backgroundColor: theme.bgCard,
      padding: 32,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: theme.border,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.25,
      shadowRadius: 25,
      elevation: 8,
    },
    logoBadge: {
      alignSelf: "center",
      width: 96,
      height: 96,
      borderRadius: 20,
      backgroundColor: "#f7f7f5",
      borderWidth: 1,
      borderColor: theme.border,
      alignItems: "center",
      justifyContent: "center",
      padding: 10,
      marginBottom: 20,
    },
    logo: {
      width: "100%",
      height: "100%",
    },
    title: {
      fontSize: 24,
      fontWeight: "700",
      color: theme.textMain,
      textAlign: "center",
      marginBottom: 6,
    },
    subtitle: {
      fontSize: 13,
      color: theme.textMuted,
      textAlign: "center",
      marginBottom: 28,
    },
    label: {
      fontSize: 14,
      fontWeight: "600",
      color: theme.textMain,
      marginBottom: 6,
    },
    input: {
      height: 46,
      fontSize: 14,
      borderRadius: 10,
      backgroundColor: theme.bgInput,
      borderWidth: 1,
      borderColor: theme.border,
      color: theme.textMain,
      paddingHorizontal: 14,
      marginBottom: 16,
    },
    inputLast: {
      height: 46,
      fontSize: 14,
      borderRadius: 10,
      backgroundColor: theme.bgInput,
      borderWidth: 1,
      borderColor: theme.border,
      color: theme.textMain,
      paddingHorizontal: 14,
    },
    helperText: {
      fontSize: 12,
      color: theme.textMuted,
      marginTop: 6,
      marginBottom: 16,
    },
    optionsRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginTop: 12,
    },
    checkboxRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    checkbox: {
      width: 18,
      height: 18,
      borderRadius: 4,
      borderWidth: 1,
      borderColor: theme.border,
      alignItems: "center",
      justifyContent: "center",
    },
    checkboxChecked: {
      backgroundColor: brand.purple,
      borderColor: brand.purple,
    },
    checkboxCheck: {
      color: "#fff",
      fontSize: 12,
      fontWeight: "700",
    },
    checkboxLabel: {
      color: theme.textMuted,
      fontSize: 12,
    },
    forgotPasswordText: {
      color: brand.purple,
      fontSize: 12,
      fontWeight: "600",
    },
    error: {
      color: "#ef4444",
      fontSize: 13,
      textAlign: "center",
      marginTop: 16,
    },
    submitButton: {
      marginTop: 24,
      borderRadius: 10,
      overflow: "hidden",
    },
    submitGradient: {
      height: 46,
      alignItems: "center",
      justifyContent: "center",
    },
    submitText: {
      color: "#fff",
      fontSize: 15,
      fontWeight: "600",
    },
    linkButton: {
      marginTop: 16,
      alignItems: "center",
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: "rgba(0,0,0,0.6)",
      justifyContent: "center",
      alignItems: "center",
      padding: 20,
    },
    modalCard: {
      width: "100%",
      maxWidth: 400,
      backgroundColor: theme.bgCard,
      padding: 24,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: theme.border,
    },
    modalTitle: {
      fontSize: 20,
      fontWeight: "700",
      color: theme.textMain,
      marginBottom: 8,
    },
    modalText: {
      fontSize: 14,
      color: theme.textMuted,
      marginBottom: 20,
    },
    modalLabel: {
      fontSize: 14,
      color: theme.textMuted,
      marginBottom: 16,
    },
    modalButtonsRow: {
      flexDirection: "row",
      gap: 12,
      marginTop: 20,
    },
    modalButtonOutline: {
      flex: 1,
      height: 44,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: theme.border,
      alignItems: "center",
      justifyContent: "center",
    },
    modalButtonOutlineText: {
      color: theme.textMain,
      fontWeight: "600",
    },
    modalButtonPrimary: {
      flex: 1,
      height: 44,
      borderRadius: 10,
      backgroundColor: brand.purple,
      alignItems: "center",
      justifyContent: "center",
    },
    modalButtonPrimaryText: {
      color: "#fff",
      fontWeight: "600",
    },
    linkText: {
      color: brand.purple,
      fontSize: 13,
    },
  });
}
